name: Integrate

on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  version:
    name: Version
    uses: cupel-co/workflows/.github/workflows/version.generate.yml@v0.21.0

  release:
    name: Release
    uses: cupel-co/workflows/.github/workflows/release.github.yml@v0.21.0
    needs:
      - version
    permissions:
      contents: write
    with:
      tag: "v${{ needs.version.outputs.sem-ver }}"
    secrets:
      google-chat-webhook-url: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
      gpg-key: "${{ secrets.GH_GPG_PRIVATE_KEY }}"
      gpg-password: "${{ secrets.GH_GPG_PRIVATE_KEY_PASSWORD }}"
      token: "${{ secrets.GH_RELEASE_PAT }}"